/**
 * AUTOR: GABRIEL GAMELEIRA DOS SANTOS
 * DATA: 25/08/2020
 * HORA: 12:03
 * FINALIDADE DE PROGRAMA: APRESENTAR FUNCOES DA API Math
 */

const raio = 5.6;

//O ATRIBUTO PI DO OBJECT Math RETORNA A CONSTANTE DE PI QUE E IGUAL A 3.14 
//A FUNCAO pow DO OBJECT Math RECEBE COMO ARGUMENTO O PRIMEIRO VALOR A BASE E O SEGUNDO ARGUMENTO O EXPOENTE
const area = Math.PI * Math.pow(raio, 2);

console.log(area);

console.log(typeof Math);