/**
 * AUTOR: GABRIEL GAMELEIRA DOS SANTOS
 * DATA: 25/08/2020
 * HORA: 12:27
 * FINALIDADE DE PROGRAMA: APRESENTAR AS FUNCOES DO TIPO String
 */ 

const escola = "Cod3r";

console.log(escola.charAt(4)); // FUNCAO charAt RECEBE COMO ARGUMENTO O VALOR QUE REPRESENTARA O INDICE QUE DEVE SER RETORNADO DA STRING 

console.log(escola.charAt(5));

console.log(escola.charCodeAt(4)); // FUNCAO charCodeAt RECEBE COMO ARGUMENTO O VALOR QUE REPRESENTARA O INDICE QUE DEVE SER RETORNADO DA STRING. O RETORNO SERA UM VALOR QUE CORRESPONDE AO SEU VALOR NA TABELA ASCCI

console.log(escola.indexOf("3")); // FUNCAO indexOf RECEBE COMO ARGUMENTO O VALOR QUE DEVE SER PROCURADO NA STRING. O RETORNO SERA O INDICE CASO SEJA ENCONTRADO O VALOR. 

console.log(escola.substring(1)); // FUNCAO substring RECEBE COMO ARGUMENTO O VALOR QUE REPRESENTARA O INDICE QUE IRA RECORTAR A STRING A PARTIR DO INDICE. O RETORNO SERA UM VALOR QUE CORRESPONDE AO RECORTE DO INDICE

console.log(escola.substring(1, 2)); // FUNCAO substring RECEBE COMO ARGUMENTO O VALOR QUE REPRESENTARA O INDICE QUE IRA RECORTAR A STRING A PARTIR DO INDICE INICIAL ATE O INDICE FINAL QUE SERA PASSADO COMO SEGUNDO ARGUMENTO. O RETORNO SERA UM VALOR QUE CORRESPONDE AO RECORTE DO INDICE

console.log('Escola '.concat(escola).concat("!")); // A FUNCAO concat RECEBE COMO ARGUMENTO UMA STRING QUE SERA CONCATENADA COM OUTRA STRING

console.log(escola.replace(3, 'e')); //A FUNCAO replace SUBSTITUI TODOS OS VALORES DE UMA STRING BASEADA NO SEU PRIMEIRO ARGUMENTO QUE E O VALOR A SER SUBSTITUIDO PELO SEGUNDO ARGUMENTO QUE E O VALOR QUE SUBSTITUIRA

console.log("ANA, MARIA, PEDRO".split(",")); //A FUNCAO SPLIT RECEBE COMO ARGUMENTO UM SEPARADOR QUE QUEBRA CADA VALOR DA STRING BASEADO NO VALOR PASSADO COMO ARGUMENTO EM UM ARRAY