/**
 * AUTOR: GABRIEL GAMELEIRA DOS SANTOS
 * DATA: 29/08/2020
 * HORA: 01:42
 * FINALIDADE DE PROGRAMA: APRESENTAR CONCEITOS RELACIONADOS AO DECLARACAO DE VARIAVEIS USANDO LET
 */

//A VARIAVEL numero DECLARADA COMO LET POSSUI O ESCOPO DE BLOCO
let numero = 1; 

{

   let numero = 2;

   console.log("Dentro = ", numero);//IRA IMPRIMIR O NUMERO DOIS 

}

console.log("Fora = ", numero);//IRA PEGAR O NUMERO UM