/**
 * AUTOR: GABRIEL GAMELEIRA DOS SANTOS
 * DATA: 24/08/2020
 * HORA: 22:47
 * FINALIDADE DE PROGRAMA: APRESENTAR A ESTRUTURA DE DECLARACAO DE VARIAVEIS
 */

//DECLARACAO DE UMA VARIAVEL COM O IDENTIFICADOR numeroA QUE RECEBE UM VALOR INTEIRO
var numeroA = 3; 

//DECLARACAO DE UMA VARIAVEL COM O IDENTIFICADOR numeroB QUE RECEBE UM VALOR INTEIRO
let numeroB = 4; 

//DECLARACAO DE UMA CONSTANTES COM O IDENTIFICADOR numeroC QUE RECEBE UM VALOR INTEIRO
const numeroC = 9;